version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: org.apache.maven:*
        versions:
          - "> 3.0.0"
          
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
    groups:
      actions-depencdencies:
        patterns:
          - "*"
          
